### PR TITLE
Testing / Module

### PR DESCRIPTION
**Pull request by Liangalvin**
Bro! I messed up your stuff on purpose... actually I tried doing testing, but it was harder then I thought. It's something I'm working on!! I'm also trying to figure out the open source part... But hopefully this kinda helps?

### CODE REVIEW

**Comment by Liangalvin** [comment]
Bro! MIT license added... but still learning on how to get it into node

**Comment by Liangalvin** [comment]
.gitignore added

**Comment by Liangalvin** [comment]
gitignore fixed?

**Comment by aadeschamps** [comment]
doesnt look like it

also, I like having the callback function named callback.

**Comment by Liangalvin** [comment]
changed param back to callback and gitignored fixed, the untracked files was a fix for the node_modules

**Comment by aadeschamps** [comment]
also, why did you module.exports the code? its front end code

**Pull request merged**
